### PR TITLE
Add 'file_type' and 'file_encoding' in section

### PR DESCRIPTION
**Pull request by Jaehaks**
Hello. 

Could you support 'file_type' and 'file_encoding' in section?

### CODE REVIEW

**Comment by tamton-aquib** [comment]
Heyyo @Jaehaks,
Just saw the issue #65 opened.

 Have you checked out the wiki examples?
https://github.com/tamton-aquib/staline.nvim/wiki/Examples

There are examples for `vim.bo.fileencoding` and `vim.bo.filetype`.

**Comment by Jaehaks** [comment]
@tamton-aquib I didn't check the tips. 
Thank you

**Comment by Jaehaks** [comment]
@tamton-aquib 
I checked the tips and inserted config like below
image

But the fileencoding don't display
image

What I missed?

**Comment by tamton-aquib** [comment]
@Jaehaks ,

Try wrapping it inside a function:

```lua
right = {
    -- ...
    function() return vim.bo.filetype:upper() end
    -- ...
}
```

**Comment by Jaehaks** [comment]
@tamton-aquib  It works! Thank you

**Pull request closed without merging**
